base:
  file_path: '<file_path(s)>'

carrier_map:
  Air Asia: ['air asia','airasia']
  Air Carnival: ['air carnival', 'aircarnival']
  air costa: ['air costa', 'aircosta']
  Air Deccan: ['air deccan', 'airdeccan']
  Air Heritage: ['airheritage', 'air heritage']
  Air India Express: ['air india express', 'airindiaexpress']
  Air India: ['air india', 'airindia']
  Air Odisha: ['airodisha']
  air pegasus: ['air pegasus', 'airpegasus']
  Air Taxi: ['air taxi']
  Alliance Air: ['alliance air', 'alliance']
  Blue Dart: ['bluedart']
  Deccan Air: ['deccan air', 'deccanair']
  FlyBig: ['flybig']
  Go Air: ['go air', 'goair']
  IndiGo: ['indigo']
  Jet Airways: ['jet airways', 'jetairways']
  JetLite: ['jetlite']
  Pawan Hans: ['pawanhans', 'pawan hans']
  QUICKJET: ['quickjetcargo','quikjetcargo']
  SpiceJet: ['spicejet']
  Star Air: ['star air', 'starair']
  TruJet: ['trujet', 'trujet', 'truejet']
  vistara: ['vistara']
  zoomair: ['zoomair']

year_map:
  2022: '22'
  2021: '21'
  2020: '20'
  2019: '19'
  2018: '18'
  2017: '17'
  2016: '16'
  2015: '15'
  2014: '14'
  2013: '13'
  2012: '12'
  2011: '11'
  2010: '10'
  2009: '09'

month_map:
  JAN: 1
  FEB: 2
  MAR: 3
  APR: 4
  MAY: 5
  JUNE: 6
  JULY: 7
  AUG: 8
  SEP: 9
  OCT: 10
  NOV: 11
  DEC: 12